# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Python Poetry Action
      # You may pin to the exact commit or the version.
      # uses: abatilo/actions-poetry@f982f3200f413c3a4d6b8f7219f74b772d77c14d
      uses: abatilo/actions-poetry@v2.1.3
      with:
        # The version of poetry to install
        poetry-version: 1.1.8
    - name: View poetry --help
      run: poetry run pytest
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install build
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
